defaults:
  - base_critic
  - hypernet_cfg: ${critic_cfg}

# These will be automatically resolved from the used environment.
reward_dim: "${env.reward_dim:${..training_cfg.env_id}}"
obs_dim: "${env.obs_dim:${..training_cfg.env_id}}"
action_dim: "${env.action_dim:${..training_cfg.env_id}}"
activation_fn: "relu"
layer_features: 
  - 256
hypernet_type: "resnet"
