defaults:
  - base_training

n_timesteps: 1_000_000
n_random_steps: 3000
env_id: "mo-hopper-v4-fork"
save_path: ???
batch_size: 128
buffer_capacity: 1_000_000
angle_deg: 45
eval_every_nth: 200
log_every_nth: 100
n_eval_episodes: 5
n_eval_prefs: 100
ref_point:
  - -100.0
  - -100.0
