defaults:
  - base_training

n_timesteps: 1_200_000
n_random_steps: 3000
env_id: "mo-swimmer-v4-fork"
save_path: ???
batch_size: 128
buffer_capacity: 1_000_000
angle_deg: 45
n_warmup_steps : "${mult:0.2, n_timesteps}"
eval_freq: 500
log_freq: 100
n_eval_episodes: 5
n_eval_prefs: 100
ref_point:
  - -100.0
  - -100.0
ref_set: "${load_json:reference_sets/mo-swimmer-v4.json}"

