defaults: 
  - base_training

n_timesteps: 10_000
n_random_steps: 500
batch_size: 128
buffer_capacity: 10_000
log_freq: 100
eval_freq: 200
n_eval_episodes: 5
n_eval_prefs: 100
env_id: "mo-hopper-v4-fork"
angle_deg: 45
save_path: "test"
ref_point: 
  - -100.0
  - -100.0
ref_set: "${load_json:reference_sets/mo-hopper-v4.json}"
