# Configuration file for MSA-hyper
defaults:
  - base_msa_hyper

n_networks: 2
alpha: 0.2
tau: 0.005
gamma: 0.995
critic_optim: "adam"
critic_lr: 3e-4
policy_optim: "adam"
policy_lr: 3e-4
device: "${..device}"

