# Configuration file for the Python's logging module
version = 1

[formatters]

[formatters.brief]
format="%(asctime)s|%(funcName)s|%(levelname)s: %(message)s"
datefmt="%d-%m-%yT%H-%M-%S"
validate=true

[formatters.verbose]
format="[%(asctime)s|%(module)s/%(funcName)s:%(lineno)d -> %(levelname)s]: %(message)s"
datefmt="%d-%m-%yT%H-%M-%S"
validate=true

[handlers]


[handlers.console]
class="logging.StreamHandler"
formatter="brief"
level="INFO"
stream="ext://sys.stdout"

[handlers.file]
class="logging.handlers.RotatingFileHandler"
formatter="verbose"
level="DEBUG"
filename="logs/run_log.log"
backupCount=10
maxBytes=10_485_760 # Limit files to 10Mb

[loggers]

[loggers.main]
handlers = ["console", "file"]
level = "DEBUG"

