# The configuration file for the logging module
version: 1

formatters:
  brief:
    format: "%(asctime)s|%(module)s/%(funcName)s|%(levelname)s: %(message)s"
    datefmt: "%d-%m-%yT%H-%M-%S"
    validate: true
  verbose:
    format: "[%(asctime)s|%(module)s/%(funcName)s:%(lineno)d -> %(levelname)s]: %(message)s"
    datefmt: "%d-%m-%yT%H-%M-%S"
    validate: true

handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: DEBUG
    stream: ext://sys.stdout

loggers:
  train:
    handlers:
      - console
    level: DEBUG
    propagate: False
  utils.nets:
    handlers: 
      - console
    level: INFO
    propagate: False
  models.msa_hyper:
    handlers: 
      - console
    level: INFO 
    propagate: False
  models.gaussian_policy:
    handlers: 
      - console
    level: INFO
    propagate: False

  models.hyper_critic:
    handlers:
      - console
    level: INFO
    propagate: False

  hypernet.headnet:
    handlers:
      - console
    level: INFO
    propagate: False
