# The configuration file for the logging module
version: 1


formatters:
  brief:
    format: 
    datefmt: 
    validate: true
  verbose:
    format: 
    datefmt: 
    validate: true

handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: verbose
    level: DEBUG
    filename: "logs/run_log.log"
    backupCount: 109
    maxBytes: 10_485_760 # 10 Mb

loggers:
  main:
    handlers:
      - console
      - file
    level: DEBUG
