defaults:
  - base_policy

policy_type: "gaussian"
activation_fn: "relu"
obs_dim: "${env.obs_dim:${..training_cfg.env_id}}"
reward_dim: "${env.reward_dim:${..training_cfg.env_id}}"
output_dim: "${env.action_dim:${..training_cfg.env_id}}"
action_space_low: "${env.action_space_low:${..training_cfg.env_id}}"
action_space_high: "${env.action_space_high:${..training_cfg.env_id}}"

layer_features: 
  - 256
  - 256

hypernet_cfg: null
