defaults:
  - base_policy

policy_type: "hyper-gaussian"
activation_fn: "relu"
obs_dim: "${env.obs_dim:${..training_cfg.env_id}}"
reward_dim: "${env.reward_dim:${..training_cfg.env_id}}"
output_dim: "${env.action_dim:${..training_cfg.env_id}}"
action_space_low: "${env.action_space_low:${..training_cfg.env_id}}"
action_space_high: "${env.action_space_high:${..training_cfg.env_id}}"

layer_features: 
  - 256
  - 256
  - 256

# Hypernet config used only if policy_type = "hyper-gaussian"
hypernet_cfg:
  head_hidden_dim: 1024
  head_init_method: "uniform"
  head_init_stds:
    - 0.05
    - 0.008
  embedding_layers:
    - n_resblocks: 2
      input_dim: "${network.input_dim:${....hypernet_inputs}, ${.....training_cfg.env_id}}"
      #input_dim: "${network.input_dim:${....hypernet_use_obs}, ${....hypernet_use_prefs}, ${....obs_dim}, ${....reward_dim}}"
      activation_fn: "relu"
      layer_features:
        - 256
        - 256
      dropout_rates:
        - 0.3
        - 0.3
    - n_resblocks: 2
      input_dim: 256
      activation_fn: "relu"
      layer_features:
        - 512
        - 512
      dropout_rates:
        - 0.2
        - 0.2

    - n_resblocks: 2
      input_dim: 512
      activation_fn: "relu"
      layer_features:
        - 1024
        - 1024
      dropout_rates:
        - 0.1
        - 0.1



