defaults:
  - base_policy

policy_type: "gaussian"
activation_fn: "relu"
obs_dim: "${env.obs_dim:${..training_cfg.env_id}}"
reward_dim: "${env.reward_dim:${..training_cfg.env_id}}"
output_dim: "${env.action_dim:${..training_cfg.env_id}}"
action_space_low: "${env.action_space_low:${..training_cfg.env_id}}"
action_space_high: "${env.action_space_high:${..training_cfg.env_id}}"
layer_features: 
  - 256
  - 256

hypernet_cfg:
  head_hidden_dim: 1024
  head_init_stds:
    - 0.05
    - 0.008
  embedding_layers:
    - n_resblocks: 2
      input_dim: "${sum:${....obs_dim}, ${....reward_dim}}"
      activation_fn: "relu"
      layer_features:
        - 256
        - 256
      dropout_rates:
        - null
        - null

    - n_resblocks: 2
      input_dim: 256
      activation_fn: "relu"
      layer_features:
        - 512
        - 512
      dropout_rates:
        - null
        - null

    - n_resblocks: 2
      input_dim: 512
      activation_fn: "relu"
      layer_features:
        - 1024
        - 1024
      dropout_rates:
        - null
        - null



